import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        <header className="w-full sticky top-0 z-20">
          <Navbar />
        </header>
        <main className="h-screen text-champagne w-full z-10 bg-gradient-to-br from-asparagus to-olivine py-2.5 px-1.5">{children}</main>
      </body>
    </html>
  );
}
